// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: user.sql

package sqlc

import (
	"context"
)

const getUsers = `-- name: GetUsers :many
SELECT id, email, password_hash, full_name, role, created_at, updated_at FROM public.users
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.FullName,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
